HAI 1.2
  I HAS A ONE ITZ 1
  I HAS A TEN ITZ 10
  
  I HAS A NUM ITZ ONE
  I HAS A NUM2 ITZ ONE
  
  IM IN YR HOUSE UPPIN YR NUM TIL BOTH SAEM NUM AN TEN
    NUM2 R ONE
    IM IN YR ROOM UPPIN YR NUM2 TIL BOTH SAEM NUM2 AN TEN
      VAR R PRODUKT OF NUM AN NUM2
      VISIBLE NUM SMOOSH "*" NUM2 " = " SMOOSH VAR MKAY
    IM OUTTA YR ROOM
    VISIBLE
  IM OUTTA YR HOUSE
KTHXBYE
